### ISSUE TITLE
Translation issues & suggest

### ISSUE THREAD

**Issue by enavap** [WazeDev/WME-ClickSaver#37]
### **Suggest**

I suggest a graphic change (to see if you like it).
[
![walking-drive 1](https://user-images.githubusercontent.com/12226761/204634950-accaef1b-8b02-4751-8cc3-c3a4b32c0e59.jpg)
](url)
The **LINE 550** describes the driving<->walking button with the following code.
_before:_
`                $button.append('<span class="fa fa-arrows-h" style="font-size:20px; color:#e84545;"></span>')`
_after:_
`                $button.append('<i class="fa fa-blind fa-lg"></i><i class="fa fa-arrows-h fa-lg" style="color:#e84545"></i><i class="fa fa-car fa-lg"></i>')`
_______________________________________________

### **Const spaceSaversGroup not defined:**

Change the **LINE 703** to the following code to make it work:
_before:_
`                        $('<label>', { class: 'cs-group-label' }).text('Time Savers'),`
_after:_
`                        $('<label>', { class: 'cs-group-label' }).text(_trans.prefs.spaceSaversGroup),`
NOTE: in the Script Translations sheet it is defined as "SPACE SAVERS" and in the Script as "TIME SAVERS".
_______________________________________________
### **Other translations**

These other phrases do not have a constant defined for translation:

1. Show "Add alt city" button
2. Show "Swap driving<->walking segment type" button
3. Add Alt City
4. Swap between driving-type and walking-type segments.
WARNING! This will DELETE and recreate the segment.  Nodes may need to be reconnected.

For options 1, 2 and 3 it is only necessary to change the following code and set the constant es in the _external translation file_:
**LINE 532:**
_before_
`                   }).text('Add alt city').click(onAddAltCityButtonClick)`
_after_
`                   }).text(_trans.prefs.addAltCity).click(onAddAltCityButtonClick)`

**LINE 706&707:**
_before_
`                            createSettingsCheckbox('csAddAltCityButtonCheckBox', 'addAltCityButton',`
`                                'Show "Add alt city" button'),`
_after_
`                            createSettingsCheckbox('csAddAltCityButtonCheckBox', 'addAltCityButton',`
`                                _trans.prefs.addAltCityButton),`

**LINE 709:**
_before_
`                                'addSwapPedestrianButton', 'Show "Swap driving<->walking segment type" button') : ''`
_after_
`                                'addSwapPedestrianButton', _trans.prefs.addSwapPedestrianButton) : ''`

Finally, move the counters to the beginning of the document.
**LINE 78:** after
`                addAltCity: 'Add Alt City',`
`                addAltCityButton: 'Show "Add alt city" button',`
`                addSwapPedestrianButton: 'Show "Swap driving<->walking segment type" button'`
_______________________________________________
For option 4 I can't help you, my knowledge of java is very little.

**Comment by mapomatic** [comment]
Thanks for the suggestions!  I do like the swap button.  I'll take a look at everything as soon as I get some time.
